name: dev-env-deployment

on:
  push:
    branches:
      - "development"

env:
  # Docker Credentials
  # DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
  # DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

  # CI Registry
  CI_REGISTRY: ghcr.io/${{ github.repository }}
  CI_REGISTRY_IMAGE: ghcr.io/${{ github.repository }}

  # APPLICATION INFO
  APPLICATION_NAME: postgres-api
  APPLICATION_NAMESPACE: postgres-api-dev
  APPLICATION_VERSION: 1.0.0-dev
  APPLICATION_PROFILE: "dev"

jobs:
  build-and-push-docker-image:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build -t $CI_REGISTRY_IMAGE:$APPLICATION_VERSION

      - name: Push Docker Image
        run: |
          docker push $CI_REGISTRY_IMAGE:$APPLICATION_VERSION
