name: Developement Environment Deployment

on:
  push:
    branches:
      - "development"
      
env:
  # APPLICATION INFO
  APPLICATION_NAME: postgres-api
  APPLICATION_NAMESPACE: postgres-api-dev
  APPLICATION_VERSION: 1.0.0-dev
  APPLICATION_PROFILE: 'dev'

jobs:
  build-and-push-docker-image:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Login to Docker
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD $CI_REGISTRY
