name: Developement Environment Deployment

on:
  push:
    branches:
      - "development"
      
env:
  # APPLICATION INFO
  APPLICATION_NAME: postgres-api
  APPLICATION_NAMESPACE: postgres-api-dev
  APPLICATION_VERSION: 1.0.0-dev
  APPLICATION_PROFILE: 'dev'

jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: check out the repo
        uses: actions/checkout@v4
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }} 
